version: "3"
services:
  portal:
    image: gentics-portal-php
    build:
      dockerfile: ./portal-files/Dockerfile
      context: .
    extra_hosts:
      - "mesh-cluster:127.0.0.1"
    volumes:
      - ./portal:/portal:cached
      - ./portal-files/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: elasticsearch:6.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
  mesh:
    # https://getmesh.io/docs/beta/administration-guide.html#_environment_variables
    image: gentics/mesh:0.22.4
    volumes:
      - meshA-config:/config
      - meshA-data:/data
      - ./mesh-shared/binaryFiles:/data/binaryFiles
      - ./mesh-shared/keystore:/keystore
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    environment:
      MESH_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      MESH_ELASTICSEARCH_START_EMBEDDED: "false"
      MESH_UPDATECHECK: "false"
      MESH_CLUSTER_ENABLED: "true"
      MESH_CLUSTER_NAME: "mesh-infra-testing-cluster"
      MESH_CLUSTER_VERTX_PORT: "4848"
      MESH_AUTH_KEYSTORE_PATH: "/keystore/keystore.jceks"
      MESH_NODE_NAME: "mesh_a"
      MESH_CLUSTER_INIT: "true"
      JAVA_TOOL_OPTIONS: "-Xms320m -Xmx320m -XX:MaxDirectMemorySize=200m"
  mesh2:
    # https://getmesh.io/docs/beta/administration-guide.html#_environment_variables
    image: gentics/mesh:0.22.4
    volumes:
      - meshB-config:/config
      - meshB-data:/data
      - ./mesh-shared/binaryFiles:/data/binaryFiles
      - ./mesh-shared/keystore:/keystore
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    environment:
      MESH_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      MESH_ELASTICSEARCH_START_EMBEDDED: "false"
      MESH_UPDATECHECK: "false"
      MESH_CLUSTER_ENABLED: "true"
      MESH_CLUSTER_NAME: "mesh-infra-testing-cluster"
      MESH_CLUSTER_VERTX_PORT: "4848"
      MESH_AUTH_KEYSTORE_PATH: "/keystore/keystore.jceks"
      MESH_NODE_NAME: "mesh_b"
      JAVA_TOOL_OPTIONS: "-Xms320m -Xmx320m -XX:MaxDirectMemorySize=200m"
  # https://hub.docker.com/r/gentics/cms/
  cms:
    image: gentics/cms:5.31
    restart: on-failure
    volumes:
      - ./cms/conf.d/include.conf:/Node/etc/conf.d/include.conf
      - ./cms/conf.d/include:/Node/etc/conf.d/include
      - ./cms/dumps:/Node/etc/dumps
      - cms-packages:/Node/node/content/packages
      - cms-dbfiles:/Node/node/content/dbfiles
      - cms-bundles:/Node/node/system/bundles
      - ./portal/public/static/demo-assets/files:/Node/node/content/packages/demo-assets/files:ro
    environment:
      NODE_DB_USER: root
      NODE_DB_PASSWORD: ""
      NODE_DB_HOST: db
      NODE_USER_PASSWORD: node
  # https://hub.docker.com/r/gentics/languagetool/
  languagetool:
    image: gentics/languagetool
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx128m"
  # https://hub.docker.com/_/mariadb/
  db:
    image: mariadb:10.3
    command: --sql-mode=""
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
volumes:
  portal-storage:
    driver: local
  portal-bootstrap-cache:
    driver: local
  meshA-config:
    driver: local
  meshA-data:
    driver: local
  meshB-config:
    driver: local
  meshB-data:
    driver: local
  elasticsearch-data:
    driver: local
  cms-packages:
    driver: local
  cms-dbfiles:
    driver: local
  cms-bundles:
    driver: local
  cms-dbfiles:
    driver: local
  db-data:
    driver: local
