services:

  portal:
    image: gentics-portal-php
    build:
      dockerfile: ./portal-files/Dockerfile
      context: .
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 200000
    environment:
      XDEBUG_ENABLED: "false"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.apa-it.at/elasticsearch/elasticsearch-oss:6.8.23
    command: >
      bash -c "[ ! -d /usr/share/elasticsearch/plugins/ingest-attachment ] \
      && bin/elasticsearch-plugin install -b ingest-attachment \
      && /usr/local/bin/docker-entrypoint.sh eswrapper"
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # https://hub.docker.com/r/gentics/mesh/
  mesh:
    # https://getmesh.io/docs/administration-guide.html#_environment_variables
    image: docker.apa-it.at/gentics/mesh:1.8.7
    volumes:
      - mesh-data:/mesh/data
      - mesh-config:/config
      - ./mesh/plugins/:/plugins/
      - ./mesh/mesh.yml:/config/mesh.yml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      JAVA_TOOL_OPTIONS: "-Xms384m -Xmx384m -XX:MaxDirectMemorySize=128m -Dstorage.diskCache.bufferSize=128"
      MESH_BINARY_DIR: "/mesh/data/uploads"
      MESH_GRAPH_DB_DIRECTORY: "/mesh/data/graphdb"
      MESH_AUTH_KEYSTORE_PATH: "/config/keystore.jceks"
      MESH_GRAPH_BACKUP_DIRECTORY: "/mesh/data/backups"
      MESH_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      MESH_ELASTICSEARCH_START_EMBEDDED: "false"
      MESH_UPDATECHECK: "false"

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # https://hub.docker.com/r/gentics/cms/
  cms:
    image: docker.apa-it.at/gentics/cms:5.44.1
    restart: on-failure
    volumes:
      - cms-node:/Node/node
      - cms-dbfiles:/Node/node/content/dbfiles
      - cms-bundles:/Node/node/system/bundles
      - ./cms/conf.d/include.conf:/Node/etc/conf.d/include.conf
      - ./cms/conf.d/include:/Node/etc/conf.d/include
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 512m
      NODE_DB_USER: root
      NODE_DB_PASSWORD: ""
      NODE_DB_HOST: db
      NODE_USER_PASSWORD: node

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # https://hub.docker.com/_/mariadb/
  db:
    image: docker.apa-it.at/mariadb:10.3
    command: --sql-mode=""
    volumes:
      - db-data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Optional: Language tool
  # Docs: https://hub.docker.com/r/gentics/languagetool/
  languagetool:
    image: docker.apa-it.at/gentics/languagetool
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx128m"

    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 192M

  # Optional: Keycloak
  # Docs: https://hub.docker.com/r/keycloak/keycloak/
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1-legacy
    restart: "no"
    environment:
      JBOSS_JAVA_SIZING: "-Xms256m -Xmx256m"
      DB_VENDOR: MARIADB
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: root
    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M

volumes:
  portal-storage:
    driver: local
  portal-bootstrap-cache:
    driver: local
  mesh-config:
    driver: local
  mesh-data:
    driver: local
  elasticsearch-data:
    driver: local
  cms-node:
    driver: local
  cms-dbfiles:
    driver: local
  cms-bundles:
    driver: local
  db-data:
    driver: local
